apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: simulation
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: reverseproxy
        tier: simulation
    spec:
      containers:
      - name: master
        image: 10.19.132.184:30100/library/simulation
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 10122
          hostPort: 10122
        - containerPort: 10022
          hostPort: 10022
