apiVersion: v1
kind: Service
metadata:
  name: test
  labels:
    app: reverseproxy
    tier: test
spec:
  type: NodePort
  ports:
  - port: 10022
    nodePort: 30022  
  selector:
    app: reverseproxy
    tier: test
